export default {
    'mj-class': {
        prefix: 'mj-class',
        body: 'mj-class="$1"',
        description: 'mj-class attribute',
        scoped: 'source.mjml',
    },
    class: {
        prefix: 'class',
        body: 'class="$1"',
        description: 'class attribute',
        scoped: 'source.mjml',
    },
    color: {
        prefix: 'color',
        body: 'color="$1"',
        description: 'color attribute',
        scoped: 'source.mjml',
    },
    width: {
        prefix: 'width',
        body: 'width="$1"',
        description: 'width attribute',
        scoped: 'source.mjml',
    },
    height: {
        prefix: 'height',
        body: 'height="$1"',
        description: 'height attribute',
        scoped: 'source.mjml',
    },
    href: {
        prefix: 'href',
        body: 'href="$1"',
        description: 'href attribute',
        scoped: 'source.mjml',
    },
    src: {
        prefix: 'src',
        body: 'src="$1"',
        description: 'src attribute',
        scoped: 'source.mjml',
    },
    id: {
        prefix: 'id',
        body: 'id="$1"',
        description: 'id attribute',
        scoped: 'source.mjml',
    },
    padding: {
        prefix: 'padding',
        body: 'padding="$1"',
        description: 'padding attribute',
        scoped: 'source.mjml',
    },
    'padding-top': {
        prefix: 'padding-top',
        body: 'padding-top="$1"',
        description: 'padding-top attribute',
        scoped: 'source.mjml',
    },
    'padding-bottom': {
        prefix: 'padding-bottom',
        body: 'padding-bottom="$1"',
        description: 'padding-bottom attribute',
        scoped: 'source.mjml',
    },
    'padding-left': {
        prefix: 'padding-left',
        body: 'padding-left="$1"',
        description: 'padding-left attribute',
        scoped: 'source.mjml',
    },
    'padding-right': {
        prefix: 'padding-right',
        body: 'padding-right="$1"',
        description: 'padding-right attribute',
        scoped: 'source.mjml',
    },
    'inner-padding': {
        prefix: 'inner-padding',
        body: 'inner-padding="$1"',
        description: 'inner-padding attribute',
        scoped: 'source.mjml',
    },
    style: {
        prefix: 'style',
        body: 'style="$1"',
        description: 'style attribute',
        scoped: 'source.mjml',
    },
    path: {
        prefix: 'path',
        body: 'path="$1"',
        description: 'path attribute',
        scoped: 'source.mjml',
    },
    align: {
        prefix: 'align',
        body: 'align="$1"',
        description: 'align attribute',
        scoped: 'source.mjml',
    },
    'vertical-align': {
        prefix: 'vertical-align',
        body: 'vertical-align="$1"',
        description: 'vertical-align attribute',
        scoped: 'source.mjml',
    },
    'font-family': {
        prefix: 'font-family',
        body: 'font-family="$1"',
        description: 'font-family attribute',
        scoped: 'source.mjml',
    },
    'font-weight': {
        prefix: 'font-weight',
        body: 'font-weight="$1"',
        description: 'font-weight attribute',
        scoped: 'source.mjml',
    },
    'line-height': {
        prefix: 'line-height',
        body: 'line-height="$1"',
        description: 'line-height attribute',
        scoped: 'source.mjml',
    },
    'letter-spacing': {
        prefix: 'letter-spacing',
        body: 'letter-spacing="$1"',
        description: 'letter-spacing attribute',
        scoped: 'source.mjml',
    },
    name: {
        prefix: 'name',
        body: 'name="$1"',
        description: 'name attribute',
        scoped: 'source.mjml',
    },
    'background-color': {
        prefix: 'background-color',
        body: 'background-color="$1"',
        description: 'background-color attribute',
        scoped: 'source.mjml',
    },
    'container-background-color': {
        prefix: 'container-background-color',
        body: 'container-background-color="$1"',
        description: 'container-background-color attribute',
        scoped: 'source.mjml',
    },
    'border-radius': {
        prefix: 'border-radius',
        body: 'border-radius="$1"',
        description: 'border-radius attribute',
        scoped: 'source.mjml',
    },
    'text-align': {
        prefix: 'text-align',
        body: 'text-align="$1"',
        description: 'text-align attribute',
        scoped: 'source.mjml',
    },
    inline: {
        prefix: 'inline',
        body: 'inline="$1"',
        description: 'inline attribute',
        scoped: 'source.mjml',
    },
    alt: {
        prefix: 'alt',
        body: 'alt="$1"',
        description: 'alt attribute',
        scoped: 'source.mjml',
    },
    lang: {
        prefix: 'lang',
        body: 'lang="$1"',
        description: 'lang attribute',
        scoped: 'source.mjml',
    },
}
